---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-releases
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s-releases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
