apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml
- metallb-config.yaml
patches:
- metallb-speaker.yaml
