apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: apps
spec:
  interval: 10m0s
  chart:
    spec:
      reconcileStrategy: ChartVersion
      chart: ./helmcharts/ingress-nginx/ingress-nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    controller:
      admissionWebhooks:
        enabled: false
      kind: DaemonSet
      watchIngressWithoutClass: true
