apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps-releases/apps/echo-server.yaml
- apps-releases/metallb-system
- helm-releases/apps/ingress-nginx.yaml
- helm-releases/kube-system/cilium.yaml
- namespaces
